fix(docs): migrate from doc_auto_cfg to doc_cfg (#832)
Close #831 

## Error

```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps
```

```
error[E0557]: feature has been removed
  --> reqsign/src/lib.rs:19:29
   |
19 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
   |                             ^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in 1.92.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
   = note: merged into `doc_cfg`

error: Compilation failed, aborting rustdoc

For more information about this error, try `rustc --explain E0557`.
error: could not document `reqsign`
```